name: CI-CD (Docker Hub)
on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:

env:
  REGISTRY: docker.io
  IMAGE_REPO: fauxapokolips/devops-k8s-app

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push (PRs will not push)
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:sha-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:latest
      - name: Run tests
        run: |
          docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:sha-${{ github.sha }} npm test

  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.29.0'
      - name: Write kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${KUBECONFIG_DATA}" | base64 -d > ~/.kube/config
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
      - name: Apply manifests
        run:
